server:
  port: 8080
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"

spring:
  datasource:
    url: jdbc:postgresql://terraform-20240327101142944900000002.cpgwwgu0sw2c.eu-west-2.rds.amazonaws.com:5432/mydatabase
    username: postgres
    password: SuperSecurePassword
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
