version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build-and-test:
    working_directory: ~/backend-app
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
          working_directory: ~/backend-app
      - run:
          name: Test
          command: mvn test
          working_directory: ~/backend-app
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/private-repo-test:${CIRCLE_BUILD_NUM} .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/private-repo-test:${CIRCLE_BUILD_NUM}
            

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test
