version: 2.1
orbs:
  docker: circleci/docker@2.6.0
  slack: circleci/slack@4.13.2

jobs:
  build-and-test:
    working_directory: ~/learner-management-service
    docker:
      - image: cimg/openjdk:17.0.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
          working_directory: ~/learner-management-service/backend-app
      - run:
          name: Test
          command: mvn test
          working_directory: ~/learner-management-service/backend-app
      - run:
          name: Build and Push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/backend:1.0.${CIRCLE_BUILD_NUM} .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/backend:1.0.${CIRCLE_BUILD_NUM}
          working_directory: ~/learner-management-service/backend-app

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "The latest Backend Docker image was built and tested successfully.",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test
      - notify:
          requires:
            - build-and-test
          context: SLACK_ACCESS
