apiVersion: v1
kind: Service
metadata:
  name: backend-app
  labels:
    app.kubernetes.io/part-of: backend-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"    
    prometheus.io/port: "backend-metric"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: backend-app
  ports:
    - name: backend-metric
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer