apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: kkushnir/circleci-team-project-frontend:0.1.14
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: docker-cred-frontend
      # env:
      #   - name: VITE_API_BASE_URL
      #     value: "a1b55c5eb26634af3b153bbfaa3fc2f1-1422858556.eu-west-2.elb.amazonaws.com"  
