apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-status
spec:
  rules:
  - host: aef69fef0cb5941e5a6ed3a362162b65-1601986578.eu-west-2.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-app
            port:
              number: 80
  ingressClassName: nginx 
