apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-status
spec:
  rules:
  - host: ab7ba1bcc03e545b8868f711c04bb6df-1899097080.eu-west-2.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-app
            port:
              number: 80
  ingressClassName: nginx 
