apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-status
spec:
  rules:
  - host: a42a1c47dcd99490fbe689e936aefaaf-19cbb30aab9e5995.elb.eu-west-2.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-app
            port:
              number: 80
  ingressClassName: nginx 
