apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-status
spec:
  rules:
  - host: a72d79c7173d24c3c87fde8e12147153-1219620796.eu-west-2.elb.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-app
            port:
              number: 80
  ingressClassName: nginx 
