version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  build:
    working_directory: ~/learner-management-service
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install vite
          command: npm i vite
          working_directory: ~/learner-management-service/frontend-app
      - run:
          name: Build
          command: npm run build
          working_directory: ~/learner-management-service/frontend-app
      - run:
          name: Build and Push Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/frontend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/frontend:$TAG
          working_directory: ~/learner-management-service/frontend-app
workflows:
  build:
    jobs:
      - build
