version: 2.1
orbs:
  docker: circleci/docker@2.6.0
  slack: circleci/slack@4.13.2

jobs:
  build:
    working_directory: ~/learner-management-service
    docker:
      - image: cimg/node:20.10.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: ~/learner-management-service/frontend-app
      - run:
          name: Build
          command: npm run build
          working_directory: ~/learner-management-service/frontend-app
      - run:
          name: Build and Push Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/frontend:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/frontend:$TAG
          working_directory: ~/learner-management-service/frontend-app

  notify:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "The latest Frontend Docker image was built successfully.",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  build_and_notify:
    jobs:
      - build
      - notify:
          requires:
            - build
          context: SLACK_ACCESS
